# Generated by Django 4.0.5 on 2022-06-12 14:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionApi', '0002_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='address',
            field=models.CharField(default='vadodara', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='caretaker',
            field=models.CharField(default='all', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='contactNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9978356585', max_length=128, region='IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
