# Generated by Django 4.0.5 on 2022-06-13 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionApi', '0003_animal_address_animal_caretaker_animal_contactnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
