# Generated by Django 4.0.5 on 2022-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionApi', '0004_animal_age_animal_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Other', 'Other')], default='Dog', max_length=10),
            preserve_default=False,
        ),
    ]
